import type { SparkLocalRpcMethod } from "@zendev-lab/spark-protocol/local-rpc-orpc-contract";

export const SPARK_WEB_RPC_ALLOWLIST = [
  "session.list",
  "channel.status",
  "session.get",
  "session.snapshot",
  "session.search",
  "session.export",
  "session.snapshot-page",
  "session.media.read",
  "session.create",
  "session.spawn",
  "session.fork",
  "session.archive",
  "session.restore",
  "session.close",
  "session.compact",
  "session.prompt-history",
  "session.model.set",
  "session.thinking.set",
  "session.retry-target",
  "turn.submit",
  "turn.status",
  "turn.stream",
  "turn.cancel",
  "turn.result",
  "invocation.list",
  "invocation.retry",
  "model.catalog",
  "model.default.set",
  "model.enabled.set",
  "provider.auth.api-key.set",
  "provider.auth.import.pi",
  "provider.auth.logout",
  "provider.auth.login.start",
  "provider.auth.login.status",
  "provider.auth.login.respond",
  "provider.auth.login.cancel",
  "artifact.list",
  "artifact.read",
  "role.list",
  "role.create",
  "role.model.list",
  "role.model.get",
  "role.model.set",
  "role.model.delete",
  "skill.list",
  "human.interaction.list",
  "human.interaction.respond",
  "workspace.ensure-local",
  "workspace.resolve-session-cwd",
  "workspace.list",
  "workspace.directory.list",
  "search.global",
  "workspace.register",
  "workspace.client.attach",
  "workspace.client.heartbeat",
  "workspace.client.release",
  "side-thread.ensure",
  "side-thread.snapshot",
  "side-thread.submit",
  "side-thread.reset",
  "side-thread.configure",
  "side-thread.handoff",
  "loop.status",
  "loop.start",
  "loop.stop",
  "loop.restart",
  "loop.wake",
  "loop.schedule",
  "repro.status",
  "daemon.status",
  "daemon.restart",
] as const satisfies readonly SparkLocalRpcMethod[];

export type SparkWebRpcMethod = (typeof SPARK_WEB_RPC_ALLOWLIST)[number];

const allowlist = new Set<string>(SPARK_WEB_RPC_ALLOWLIST);

export function isAllowedSparkWebRpcMethod(method: string): method is SparkWebRpcMethod {
  return allowlist.has(method);
}
